### ISSUE TITLE
Settings occasionally reset, until something is flicked off n on again.

### ISSUE THREAD

**Issue by JesusLuvsYooh** [Gawah/MangoPeel#7] opened 2023-08-11 13:31 UTC
Take note the top bar, customise your mango layout, play a game, sleep/suspend or something, and it will have reset.
To re-activate some of your customised settings, flick any toggle in mango off and on and it re-applies it.
I hope this sheds some light on a bug, thats minor but irritating!  :D

![Screenshot 2023-08-11 at 14 26 40](https://github.com/Gawah/MangoPeel/assets/57072365/f3f4b9d3-38e0-4271-a58d-77ff5d3091a7)

![Screenshot 2023-08-11 at 14 26 57](https://github.com/Gawah/MangoPeel/assets/57072365/92b93ed9-3780-47ed-bdbb-488f32b56ffc)

Video preview:  (check top bar)

https://github.com/Gawah/MangoPeel/assets/57072365/44663ee1-19d4-4bc9-817c-9d82a82da3f0

**Comment by Rika-TH** [comment] 2023-08-12 01:42
This seems to be newish, just set a minimal layout 1 for base use with just battery and gamescope but on refresh (reboot gaming mode/system etc.) It enables EVERY CPU core 4xing the area it takes up

**Comment by Rika-TH** [comment] 2023-08-12 01:42
If needed I can provide my configs

**Comment by Gawah** [comment] 2023-08-12 03:50
> Take note the top bar, customise your mango layout, play a game, sleep/suspend or something, and it will have reset. To re-activate some of your customised settings, flick any toggle in mango off and on and it re-applies it. I hope this sheds some light on a bug, thats minor but irritating! :D
> 
> ![Screenshot 2023-08-11 at 14 26 40](https://user-images.githubusercontent.com/57072365/260019638-f3f4b9d3-38e0-4271-a58d-77ff5d3091a7.jpg)
> 
> ![Screenshot 2023-08-11 at 14 26 57](https://user-images.githubusercontent.com/57072365/260019706-92b93ed9-3780-47ed-bdbb-488f32b56ffc.jpg)
> 
> Video preview: (check top bar)
> 
>  Decky-RecorderMango1.mp4
Is this issue occurring randomly or is it happening consistently? On my Steam Deck, when I start a game or suspend the system, it does not cause the settings to reset.

**Comment by Gawah** [comment] 2023-08-12 03:51
> Take note the top bar, customise your mango layout, play a game, sleep/suspend or something, and it will have reset. To re-activate some of your customised settings, flick any toggle in mango off and on and it re-applies it. I hope this sheds some light on a bug, thats minor but irritating! :D
> 
> ![Screenshot 2023-08-11 at 14 26 40](https://user-images.githubusercontent.com/57072365/260019638-f3f4b9d3-38e0-4271-a58d-77ff5d3091a7.jpg)
> 
> ![Screenshot 2023-08-11 at 14 26 57](https://user-images.githubusercontent.com/57072365/260019706-92b93ed9-3780-47ed-bdbb-488f32b56ffc.jpg)
> 
> Video preview: (check top bar)
> 
>  Decky-RecorderMango1.mp4

Is this issue occurring randomly or is it happening consistently? On my Steam Deck, when I start a game or suspend the system, it does not cause the settings to reset.

**Comment by Rika-TH** [comment] 2023-08-12 09:55
On my end it is every time I reboot or swap from desktop to gaming, no other time @Gawah happened 100% so far (about 10-20 resets over the last few hrs)

**Comment by JesusLuvsYooh** [comment] 2023-08-12 12:01
Could be as Rika-TH said above, i do tend to swap modes/reboot frequently lately.

> > Take note the top bar, customise your mango layout, play a game, sleep/suspend or something, and it will have reset. To re-activate some of your customised settings, flick any toggle in mango off and on and it re-applies it. I hope this sheds some light on a bug, thats minor but irritating! :D
> > ![Screenshot 2023-08-11 at 14 26 40](https://user-images.githubusercontent.com/57072365/260019638-f3f4b9d3-38e0-4271-a58d-77ff5d3091a7.jpg)
> > ![Screenshot 2023-08-11 at 14 26 57](https://user-images.githubusercontent.com/57072365/260019706-92b93ed9-3780-47ed-bdbb-488f32b56ffc.jpg)
> > Video preview: (check top bar)
> > Decky-RecorderMango1.mp4
> 
> Is this issue occurring randomly or is it happening consistently? On my Steam Deck, when I start a game or suspend the system, it does not cause the settings to reset.

**Comment by Gawah** [comment] 2023-09-10 07:00
I'm sorry, I was busy last month and didn't have time to investigate this issue. It seems to be caused by the failure of the pyinotify module in the main channel, while I had only tested it in the stable channel before. This issue should be fixed in v0.0.3.

**Closed** 2023-09-11 07:54 UTC
